name: CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get upgrade -y
      - run: pip install -r requirements.txt
      - run: pytest-cov -v
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker build . --env-file -t yamessdockerhub/python-grpc:$(BuildAgent.Build) yamessdockerhub/python-grpc:latest
